from pathlib import Path
root=Path('/tmp/gmcsite')
common='''
<style>
.policy-wrap{width:90%;max-width:1050px;margin:auto;padding:55px 0 70px}.policy-hero{text-align:center;padding:5px 15px 38px}.policy-kicker{color:#ff2929;font-size:11px;font-weight:900;letter-spacing:2.5px}.policy-hero h1{font-size:46px;line-height:1.08;margin:10px 0 12px;font-weight:1000}.policy-hero h1 span{color:#ff1717}.policy-hero p{max-width:700px;margin:auto;color:#888;font-size:13px;line-height:1.7}.policy-card{border:1px solid rgba(255,0,0,.35);border-radius:16px;background:linear-gradient(145deg,rgba(255,0,0,.055),rgba(255,255,255,.018));box-shadow:0 0 45px rgba(255,0,0,.045);padding:30px 32px}.policy-section{padding:0 0 25px;margin:0 0 25px;border-bottom:1px solid rgba(255,255,255,.07)}.policy-section:last-child{border-bottom:0;margin-bottom:0;padding-bottom:0}.policy-section h2{font-size:17px;margin-bottom:10px;color:#fff}.policy-section h2:before{content:'';display:inline-block;width:5px;height:17px;background:#ff1717;margin-right:10px;vertical-align:-3px;box-shadow:0 0 12px rgba(255,0,0,.55)}.policy-section p,.policy-section li{color:#999;font-size:12px;line-height:1.85}.policy-section ul{padding-left:19px;margin-top:8px}.policy-section li{margin:5px 0}.policy-note{border:1px solid rgba(255,0,0,.25);border-radius:10px;background:rgba(255,0,0,.045);padding:14px 16px;color:#aaa;font-size:11px;line-height:1.7;margin-top:15px}.policy-note strong{color:#ff3030}.policy-date{color:#666;text-align:right;font-size:10px;margin-top:22px}.policy-links{display:flex;gap:10px;flex-wrap:wrap;justify-content:center;margin-top:25px}.policy-links a{color:#aaa;text-decoration:none;border:1px solid #272727;border-radius:8px;padding:9px 12px;font-size:10px;font-weight:800}.policy-links a:hover{border-color:#ff2525;color:#fff}footer{text-align:center;border-top:1px solid rgba(255,0,0,.13);padding:22px;color:#555;font-size:10px;line-height:2}footer span{color:#ff2525}footer .footer-links{display:flex;justify-content:center;gap:8px 16px;flex-wrap:wrap;margin-top:6px}footer .footer-links a{color:#777;text-decoration:none;font-weight:700}footer .footer-links a:hover{color:#ff2929}@media(max-width:600px){.policy-wrap{width:92%;padding-top:35px}.policy-hero h1{font-size:34px}.policy-card{padding:22px 20px}.policy-section p,.policy-section li{font-size:11px}}
</style>
'''
nav='''<nav><a href="first.html" class="logo">GMC</a><div class="nav-links"><a href="first.html">HOME</a><a href="product.html">PRODUCTS</a><a href="contact.html">CONTACT</a></div></nav>'''
base_style='''<style>*{margin:0;padding:0;box-sizing:border-box;font-family:Arial,Helvetica,sans-serif}html{scroll-behavior:smooth}body{background:#050505;color:#fff;min-height:100vh;overflow-x:hidden}.bg{position:fixed;inset:0;z-index:-10;background:radial-gradient(circle at 10% 15%,rgba(255,0,0,.12),transparent 28%),radial-gradient(circle at 88% 72%,rgba(255,0,0,.09),transparent 30%),#050505}.grid{position:absolute;inset:0;opacity:.16;background-image:linear-gradient(rgba(255,255,255,.025) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.025) 1px,transparent 1px);background-size:50px 50px}nav{height:78px;padding:0 7%;display:flex;align-items:center;justify-content:space-between;background:rgba(5,5,5,.76);backdrop-filter:blur(18px);border-bottom:1px solid rgba(255,0,0,.14);position:sticky;top:0;z-index:20}.logo{color:#fff;text-decoration:none;font-size:21px;font-weight:1000;letter-spacing:1.5px}.nav-links{display:flex;align-items:center;gap:27px}.nav-links a{color:#888;text-decoration:none;font-size:12px;font-weight:800;letter-spacing:.5px}.nav-links a:hover{color:#fff}.nav-links a:after{content:'';display:block;width:0;height:2px;margin-top:8px;background:#ff1111;box-shadow:0 0 10px red;transition:.3s}.nav-links a:hover:after{width:100%}@media(max-width:600px){nav{padding:0 5%}.logo{font-size:17px}.nav-links{gap:12px}.nav-links a{font-size:9px}}
</style>'''
footer='''<footer><div>© 2026 <span>GMC</span>. All Rights Reserved.</div><div class="footer-links"><a href="privacy-policy.html">Privacy Policy</a><a href="terms-conditions.html">Terms &amp; Conditions</a><a href="refund-cancellation.html">Refund &amp; Cancellation</a><a href="shipping-delivery.html">Shipping &amp; Delivery</a></div></footer>'''

data={
'privacy-policy.html':('PRIVACY POLICY','YOUR PRIVACY MATTERS','This Privacy Policy explains how GMC may collect, use, store and protect information when you use our website, purchase a digital product, or contact our support team.',[
('1. Information We Collect','We may collect information you provide during checkout or support requests, such as your name, email address, contact number, order details and payment-related reference information. Payment credentials such as card, UPI or banking details are processed by our payment provider and are not intentionally stored by GMC.'),
('2. How We Use Information','We use information to process orders, deliver purchased digital products, send transaction or delivery emails, provide customer support, prevent abuse or fraudulent activity, maintain service records, and improve the website.'),
('3. Digital Product Credentials','Where a purchase includes a license key or username and password, those credentials are provided to the customer for the purchased service. Customers should keep them confidential and should not publish or share them publicly.'),
('4. Payments & Third Parties','Payments may be processed through Razorpay and transactional emails may be delivered through third-party email infrastructure. Those providers may process information according to their own privacy policies and applicable terms.'),
('5. Data Security','We take reasonable technical and organizational measures to protect information from unauthorized access, loss, misuse or disclosure. However, no online service can guarantee absolute security.'),
('6. Data Retention','We retain order and support information for as long as reasonably necessary for order fulfillment, customer support, accounting, security, dispute resolution and legal or regulatory requirements.'),
('7. Cookies & Similar Technologies','The website may use essential browser storage, cookies or similar technologies to maintain sessions, remember preferences, operate checkout and improve functionality.'),
('8. Your Choices','You may contact GMC to request clarification about information associated with your order or to raise a privacy concern. Some information may need to be retained where required for legitimate business, security or legal purposes.'),
('9. Policy Updates','We may update this policy when our services, technology or legal requirements change. The updated version will be posted on this page.'),
]),
' terms-conditions.html'.strip():('TERMS & CONDITIONS','PLEASE READ BEFORE PURCHASE','These Terms & Conditions govern your use of the GMC website and purchase of GMC digital products. By using the website or completing a purchase, you agree to these terms.',[
('1. Digital Products','GMC primarily provides digital products and services. Product descriptions, plans, prices, availability and included features are shown on the website and may change from time to time.'),
('2. Orders & Payment','An order is created when you proceed through checkout. Payment is processed through the available payment gateway. GMC may refuse, cancel or review an order where payment information appears invalid, duplicated, fraudulent or inconsistent with the order.'),
('3. Delivery','After successful payment verification, the purchased digital product or credentials may be delivered electronically to the email address supplied during checkout. Customers are responsible for providing a correct and accessible email address.'),
('4. License / Account Credentials','If a plan provides a license key, username or password, it is intended for the purchased customer and service only. Do not resell, publish, share, reverse engineer, abuse or attempt to bypass restrictions associated with the product.'),
('5. Website Use','You must not use the website for unlawful activity, fraud, abuse, automated attacks, unauthorized access, interference with the service, or activity that could harm GMC or other users.'),
('6. Availability','GMC aims to keep the website and purchased services available, but temporary downtime, maintenance, third-party outages or technical problems may occur. Availability of a particular product is subject to current inventory.'),
('7. Intellectual Property','The GMC website, branding, original content, interface design and other materials provided by GMC are protected by applicable intellectual-property laws. You may not copy or redistribute GMC materials except where expressly permitted.'),
('8. Limitation','To the extent permitted by applicable law, GMC is not responsible for indirect losses, third-party service interruptions, incorrect customer information, or misuse of credentials by the customer.'),
('9. Changes','GMC may update these terms, product offerings or website functionality. Continued use after an update constitutes acceptance of the revised terms.'),
]),
'refund-cancellation.html':('REFUND & CANCELLATION','PURCHASE & REFUND INFORMATION','Because GMC products are digital, cancellation and refund requests are handled according to the status of the order and whether the digital product or credentials have already been delivered.',[
('1. Before Successful Payment','If payment has not been successfully completed, no order delivery takes place. Customers may simply stop the payment process.'),
('2. Payment Successful but Delivery Failed','If your payment was successfully captured but you did not receive the purchased digital product or credentials, contact GMC support with your order details. We will verify the payment and attempt to resolve the delivery issue or provide an appropriate remedy.'),
('3. After Digital Delivery','Once a license key or account credentials have been successfully delivered, refunds may be restricted because the digital item can no longer be treated like an unused physical product. Any request will be reviewed based on the circumstances of the order.'),
('4. Duplicate or Incorrect Charges','If you believe you were charged more than once for the same order, contact GMC with the relevant payment/order reference. Verified duplicate payments will be investigated and handled appropriately.'),
('5. Cancellation','A purchase cannot always be cancelled after payment verification or credential reservation. If you need to cancel, contact support as soon as possible and before the digital item is delivered where possible.'),
('6. How to Request Help','Send your order/payment reference, purchase email and a short description of the issue through the GMC contact page. Do not send your full card number, CVV, UPI PIN or other sensitive payment credentials.'),
('7. Processing','Refunds, where approved, are normally returned through the payment method or process supported by the payment provider and may take additional processing time outside GMC control.'),
]),
'shipping-delivery.html':('SHIPPING & DELIVERY','DIGITAL DELIVERY POLICY','GMC products are delivered electronically. No physical package is normally shipped for digital products purchased through this website.',[
('1. Delivery Method','Purchased digital products are delivered electronically using the email address provided during checkout and/or the download link shown as part of the order flow.'),
('2. Delivery Timing','After payment is successfully verified, GMC processes the order and sends the applicable digital delivery. Delivery is generally automated, but technical or payment-provider delays can occasionally occur.'),
('3. What You May Receive','Depending on the selected plan, delivery may include a license key, username and password, a download link, order information, or a combination of these items.'),
('4. Customer Responsibility','Please enter a valid email address and check your inbox, spam, promotions and other filtered folders after purchase. Keep delivered credentials private and secure.'),
('5. Payment Pending','If a payment is pending or has not been successfully verified, the order may not be delivered yet. Do not make repeated payments unless the payment status confirms that the previous attempt failed.'),
('6. Delivery Problems','If you have completed payment but have not received the delivery, contact GMC support with your order/payment reference and purchase email. We will verify the transaction and assist with delivery.'),
('7. Physical Shipping','GMC does not normally ship physical goods under the digital product offerings covered by this policy. Therefore, shipping charges and physical courier tracking generally do not apply.'),
])}

for fn,(title,kicker,desc,sections) in data.items():
    html=f'''<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="description" content="{desc}"><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='14' fill='%23050505'/%3E%3Ctext x='32' y='45' text-anchor='middle' font-family='Arial' font-size='42' font-weight='900' fill='%23ff1010'%3EG%3C/text%3E%3C/svg%3E"><title>GMC — {title.title()}</title>{base_style}{common}</head><body><div class="bg"><div class="grid"></div></div>{nav}<main class="policy-wrap"><section class="policy-hero"><div class="policy-kicker">{kicker}</div><h1>{title.replace('&','&amp;').replace(' ',' <span>',1) if False else title.replace('POLICY','<span>POLICY</span>') if title=='PRIVACY POLICY' else title}</h1><p>{desc}</p></section><section class="policy-card">'''
    for h,p in sections:
        html+=f'<article class="policy-section"><h2>{h}</h2><p>{p}</p></article>'
    html+='''<div class="policy-note"><strong>Important:</strong> These pages provide the website's current policies for GMC digital products. If you have an order-specific question, please contact GMC support before making assumptions about eligibility or delivery.</div><div class="policy-links"><a href="privacy-policy.html">Privacy Policy</a><a href="terms-conditions.html">Terms &amp; Conditions</a><a href="refund-cancellation.html">Refund &amp; Cancellation</a><a href="shipping-delivery.html">Shipping &amp; Delivery</a><a href="contact.html">Contact GMC</a></div><div class="policy-date">Last updated: September 11, 2026</div></section></main>'''+footer+'''</body></html>'''
    (root/fn).write_text(html,encoding='utf-8')
